# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master-2

pool:
  vmImage: ubuntu-latest

steps:
# CMake v1
# Build with the CMake cross-platform build system.
- task: CMake@1
  inputs:
    workingDirectory: '.' # string. Alias: cwd. Working Directory. Default: build.
    cmakeArgs: -DCMAKE_TOOLCHAIN_FILE=$(VCPKG_ROOT)/scripts/buildsystems/vcpkg.cmake --preset Linux-GCC-Release
  # Advanced
    #runInsideShell: false # boolean. Run cmake command inside shell. Default: false.
